name: ecos_main
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  flutter_emoji_feedback: ^0.4.0
  flutter_rating: ^2.0.2
  intl: ^0.19.0
  flutter_svg: ^2.0.17
  uuid: ^4.5.1
  go_router: ^14.6.3
  hooks_riverpod: ^2.6.1
  json_theme_plus: ^6.6.1
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.3
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/themes/light_theme.json
    - assets/themes/dark_theme.json

