name: ecos_main
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared:
    path: ./lib/shared

  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.6.1
  json_theme_plus: ^6.6.1


flutter:

  assets:
    - assets/icons/
    - assets/themes/light_theme.json
    - assets/themes/dark_theme.json

dev_dependencies:
  flutter_test:
    sdk: flutter
